version: "3.3"
services:
  backend:
    build:
      context: ./
      dockerfile: Backend_Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ./srcs/backend:/usr/src/app
    #   - /usr/src/app/node_modules
    depends_on:
      - "dbservice"
    restart: always
    container_name: "backend"
    image: backend

  dbservice:
    image: postgres
    restart: always
    env_file:
      - ./srcs/.env
    container_name: "dbservice"
    volumes:
      - pgdata:/var/lib/postgresql/data

  client:
    # volumes:
    # - ./srcs/client:/usr/src/app
    # -  /usr/src/app/node_modules
    build:
      context: ./
      dockerfile: Client_Dockerfile
    container_name: "client"
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - "backend"
    image: client
    command: serve -l 5000 -s ./dist

volumes:
  pgdata:
